sudo: required
language: python
os: linux
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
matrix:
  allow_failures:
    - python: "3.5"
    - python: "3.7-dev"

env:
  #- TRAVIS_JDK_VERSION=oraclejdk8
  - TRAVIS_JDK_VERSION=oraclejdk9
  #- TRAVIS_JDK_VERSION=openjdk8

before_install:
  - |
    set -e
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update
      brew install pyenv || brew upgrade pyenv
      pyenv install "${TRAVIS_PYTHON_VERSION}"
      export PATH="$HOME/.pyenv/versions/${TRAVIS_PYTHON_VERSION}/bin:${PATH}"
    fi
    set +e
  - |
    set -e
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      jdk_switcher use $TRAVIS_JDK_VERSION
    fi
    set +e
  # Open Fortran Compiler
  - git clone "https://github.com/codethinklabs/ofc" "../open-fortran-compiler"
  - cd "../open-fortran-compiler" && make && cd -
  - export PATH="${PATH}:$(pwd)/../open-fortran-compiler"
  # FFB-MINI app
  - git clone "https://github.com/mbdevpl/ffb-mini" "../ffb-mini" --branch ofp_tests
  # miranda_io app
  - git clone "https://github.com/mbdevpl/miranda_io" "../miranda_io"

install:
  - pip install -U pip
  - pip install -U -r dev_requirements.txt

script:
  - TEST_PACKAGING=1 python -m coverage run --branch --source . -m unittest discover --verbose

after_success:
  - python -m coverage report --show-missing
  - codecov
  - python -m pylint --load-plugins=pylint.extensions.mccabe --docstring-min-length 5 --no-docstring-rgx "^(test)?_|.*Tests$" --unsafe-load-any-extension y --output-format colorized  --reports y $(find . -name "*.py")

notifications:
  slack:
    secure: "IJLucZng9JvlxZY6jm17YZ1Ehy528T47Gsz3ztYpZlZIvPCfprGPSK7Cj0kOQRpsSBw73aWXt+f9akggq81seQZabSahI/Lun5vKaoasuNveUElbnw0bsQRrpUyFrWH1pYQndxd6Rpd2YOek6fxS0+PbVoX4Gwg3Z7EDgfaL5MWdlmkEkUdwsZzSK+zmJyEWkWHeyCYd29760gRK85bzTBG/Y/yDrxS7xUnU5OgiUHg5U6LKfyoWKwSW0o2ljkCs72/xSVwYqPNg5MEixExfvmQgElnsp2Bn/KJcPa6HZYnTTsL1d0TBC59C3imRkSZztR1Fmg39r72Lq0W0EMdwJzTKwlGgYxdPuCfCdkM+rhmlOHjYwq56oWBOu+jT8vVbgNsxeFAEmqwtLJ7b7K4OCkiyFwdGWy9DvbJ2vhq4hwjRCMfXVDpTmgP7fNj8Tc05ZpnM8gwk9w54/Vv0taYFguocgj7VbNpJfl2cnQbRG3Zj/AQ5vtmkhDnU/0mDQ4j4lOQuuJ+BeJ0p6qEl1JVGYDRXBg/YfRdRR0uT/wY1gZNQwJ7byrgC0Al+WrRTXkB6ds9+/JlP5o9la7BImtaMOkUBkPCTg0XsRZ/aVTAHMPSrSrOxUXl4imTJHg7R75EYvtXo5aEnPLMorJldaZfTyZFLhf2nnYQ4K4WX3Cm8uQI="
  email: false
