language: generic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ant
      # - gcc-7
      # - gfortran-7
      # - g++-7
      - gfortran
      - swig
  homebrew:
    packages:
      - ant
      - gcc
      - llvm
      - pyenv
      - swig
matrix:
  include:
    - os: linux
      language: python
      python: "3.5"
    - os: linux
      language: python
      python: "3.6"
    - os: linux
      language: python
      python: "3.7"
    - os: osx
      osx_image: xcode11
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.5"
    - os: osx
      osx_image: xcode11
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.6"
    - os: osx
      osx_image: xcode11
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.7"
  allow_failures:
    - python: "3.7"
    - env: TRAVIS_PYTHON_VERSION="3.7"

before_install:
  - .build/choose_gcc.sh 8
  - |
    set -e
    if [[ "$(uname)" == "Darwin" ]]; then
      export PATH="/usr/local/opt/llvm/bin:${PATH}"
      export LLVM_DIR=$(llvm-config --prefix)
      echo "${LLVM_DIR}"
      # find / -name "LLVMConfig.cmake" 2>/dev/null
      # find / -name "llvm-config.cmake" 2>/dev/null
      # ls -lah /usr/local/bin
      # ls -lah /opt/local/bin
      mkdir /tmp/includes
      brew doctor 2>&1 | grep "/usr/local/include" | awk '{$1=$1;print}' | xargs -I _ mv _ /tmp/includes
    fi
    set +e
  - gcc --version
  - g++ --version
  - swig -version
  - gfortran --version
  - java --version
  - .build/install_pyenv.sh
  # apps
  - git clone "https://github.com/mbdevpl/ffb-mini" "../ffb-mini"
  - git clone "https://github.com/ECP-Astro/FLASH5.git" "../flash5"
  - git clone "https://github.com/mbdevpl/miranda_io" "../miranda_io"

install:
  - .build/install_open_fortran_compiler.sh
  - .build/install_castxml.sh
  - pip install -U pip
  - .build/install_open_fortran_parser_xml.sh
  - pip install -U -r ci_requirements.txt

script:
  - if [[ "${TRAVIS_PYTHON_VERSION}" == "3.6" ]]; then TEST_PACKAGING=1 TEST_LONG=1; fi
  - python -m coverage run --branch --source . -m unittest -v

after_success:
  - python -m coverage report --show-missing
  - codecov

notifications:
  slack:
    secure: "IJLucZng9JvlxZY6jm17YZ1Ehy528T47Gsz3ztYpZlZIvPCfprGPSK7Cj0kOQRpsSBw73aWXt+f9akggq81seQZabSahI/Lun5vKaoasuNveUElbnw0bsQRrpUyFrWH1pYQndxd6Rpd2YOek6fxS0+PbVoX4Gwg3Z7EDgfaL5MWdlmkEkUdwsZzSK+zmJyEWkWHeyCYd29760gRK85bzTBG/Y/yDrxS7xUnU5OgiUHg5U6LKfyoWKwSW0o2ljkCs72/xSVwYqPNg5MEixExfvmQgElnsp2Bn/KJcPa6HZYnTTsL1d0TBC59C3imRkSZztR1Fmg39r72Lq0W0EMdwJzTKwlGgYxdPuCfCdkM+rhmlOHjYwq56oWBOu+jT8vVbgNsxeFAEmqwtLJ7b7K4OCkiyFwdGWy9DvbJ2vhq4hwjRCMfXVDpTmgP7fNj8Tc05ZpnM8gwk9w54/Vv0taYFguocgj7VbNpJfl2cnQbRG3Zj/AQ5vtmkhDnU/0mDQ4j4lOQuuJ+BeJ0p6qEl1JVGYDRXBg/YfRdRR0uT/wY1gZNQwJ7byrgC0Al+WrRTXkB6ds9+/JlP5o9la7BImtaMOkUBkPCTg0XsRZ/aVTAHMPSrSrOxUXl4imTJHg7R75EYvtXo5aEnPLMorJldaZfTyZFLhf2nnYQ4K4WX3Cm8uQI="
  email: false
