sudo: required
language: generic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ant
      - gcc-7
      - gfortran-7
      - g++-7
      - swig
  homebrew:
    packages:
      - ant
      - gcc
      - llvm
      - pyenv
matrix:
  include:
    - os: linux
      language: python
      python: "3.5"
    - os: linux
      language: python
      python: "3.6"
    - os: linux
      dist: xenial
      sudo: true
      language: python
      python: "3.7"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.5"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.6"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.7"
  allow_failures:
    - python: "3.7"
    - env: TRAVIS_PYTHON_VERSION="3.7"

env:
  - TRAVIS_JDK_VERSION=oraclejdk9

before_install:
  - mkdir -p "${HOME}/.local/bin"
  - |
    set -e
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo update-alternatives \
        --install /usr/local/bin/gcc gcc /usr/bin/gcc-7 70 \
        --slave /usr/local/bin/g++ g++ /usr/bin/g++-7 \
        --slave /usr/local/bin/cpp gcc-cpp /usr/bin/cpp-7 \
        --slave /usr/local/bin/gfortran gfortran /usr/bin/gfortran-7 \
        --slave /usr/local/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-7 \
        --slave /usr/local/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-7 \
        --slave /usr/local/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-7 \
        --slave /usr/local/bin/gcov gcov /usr/bin/gcov-7 \
        --slave /usr/local/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-7
      sudo update-alternatives --install /usr/bin/cc cc /usr/local/bin/gcc 100
      sudo update-alternatives --install /usr/bin/c++ c++ /usr/local/bin/g++ 100
      sudo update-alternatives --install /lib/cpp cpp /usr/local/bin/cpp 100
      sudo update-alternatives --install /usr/bin/f77 f77 /usr/local/bin/gfortran 100
      sudo update-alternatives --install /usr/bin/f95 f95 /usr/local/bin/gfortran 100
    else
      sudo ln -s /usr/local/bin/gcc-8 /usr/local/bin/gcc
      sudo ln -s /usr/local/bin/g++-8 /usr/local/bin/g++
      sudo ln -s /usr/local/bin/cpp-8 /usr/local/bin/cpp
      # sudo ln -s /usr/local/bin/gfortran-8 /usr/local/bin/gfortran  # already exists
      sudo ln -s /usr/local/bin/gcc-ar-8 /usr/local/bin/gcc-ar
      sudo ln -s /usr/local/bin/gcc-nm-8 /usr/local/bin/gcc-nm
      sudo ln -s /usr/local/bin/gcc-ranlib-8 /usr/local/bin/gcc-ranlib
      sudo ln -s /usr/local/bin/gcov-8 /usr/local/bin/gcov
      sudo ln -s /usr/local/bin/gcov-dump-8 /usr/local/bin/gcov-dump
      export PATH="/usr/local/opt/llvm/bin:${PATH}"
      export LLVM_DIR=$(llvm-config --prefix)
      echo "${LLVM_DIR}"
      # find / -name "LLVMConfig.cmake" 2>/dev/null
      # find / -name "llvm-config.cmake" 2>/dev/null
      # ls -lah /usr/local/bin
      # ls -lah /opt/local/bin
      mkdir /tmp/includes
      brew doctor 2>&1 | grep "/usr/local/include" | awk '{$1=$1;print}' | xargs -I _ mv _ /tmp/includes
    fi
    set +e
  - gcc --version
  - g++ --version
  - gfortran --version
  - .travis/install_pyenv.sh
  - |
    set -e
    if [[ "${TRAVIS_OS_NAME}" == "linux" && "${TRAVIS_PYTHON_VERSION}" != "3.7" ]]; then
      jdk_switcher use $TRAVIS_JDK_VERSION
    fi
    set +e
  # apps
  - git clone "https://github.com/mbdevpl/ffb-mini" "../ffb-mini"
  - git clone "https://github.com/ECP-Astro/FLASH5.git" "../flash5"
  - git clone "https://github.com/mbdevpl/miranda_io" "../miranda_io"

install:
  - .travis/install_open_fortran_compiler.sh
  - .travis/install_castxml.sh
  - pip install -U pip
  - .travis/install_open_fortran_parser_xml.sh
  - pip install -U -r dev_requirements.txt

script:
  - TEST_PACKAGING=1 TEST_LONG=1 python -m coverage run --branch --source . -m unittest -v

after_success:
  - python -m coverage report --show-missing
  - codecov

notifications:
  slack:
    secure: "IJLucZng9JvlxZY6jm17YZ1Ehy528T47Gsz3ztYpZlZIvPCfprGPSK7Cj0kOQRpsSBw73aWXt+f9akggq81seQZabSahI/Lun5vKaoasuNveUElbnw0bsQRrpUyFrWH1pYQndxd6Rpd2YOek6fxS0+PbVoX4Gwg3Z7EDgfaL5MWdlmkEkUdwsZzSK+zmJyEWkWHeyCYd29760gRK85bzTBG/Y/yDrxS7xUnU5OgiUHg5U6LKfyoWKwSW0o2ljkCs72/xSVwYqPNg5MEixExfvmQgElnsp2Bn/KJcPa6HZYnTTsL1d0TBC59C3imRkSZztR1Fmg39r72Lq0W0EMdwJzTKwlGgYxdPuCfCdkM+rhmlOHjYwq56oWBOu+jT8vVbgNsxeFAEmqwtLJ7b7K4OCkiyFwdGWy9DvbJ2vhq4hwjRCMfXVDpTmgP7fNj8Tc05ZpnM8gwk9w54/Vv0taYFguocgj7VbNpJfl2cnQbRG3Zj/AQ5vtmkhDnU/0mDQ4j4lOQuuJ+BeJ0p6qEl1JVGYDRXBg/YfRdRR0uT/wY1gZNQwJ7byrgC0Al+WrRTXkB6ds9+/JlP5o9la7BImtaMOkUBkPCTg0XsRZ/aVTAHMPSrSrOxUXl4imTJHg7R75EYvtXo5aEnPLMorJldaZfTyZFLhf2nnYQ4K4WX3Cm8uQI="
  email: false
