sudo: required
language: generic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ant
      - gcc-7
      - gfortran-7
      - g++-7
      - swig
  homebrew:
    packages:
      - ant
      - gcc
      - pyenv
matrix:
  include:
    - os: linux
      language: python
      python: "3.5"
    - os: linux
      language: python
      python: "3.6"
    - os: linux
      dist: xenial
      sudo: true
      language: python
      python: "3.7"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.5"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.6"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.7"
  allow_failures:
    - python: "3.7"
    - env: TRAVIS_PYTHON_VERSION="3.5"
    - env: TRAVIS_PYTHON_VERSION="3.6"
    - env: TRAVIS_PYTHON_VERSION="3.7"

env:
  - TRAVIS_JDK_VERSION=oraclejdk9

before_install:
  - |
    set -e
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo update-alternatives \
        --install /usr/local/bin/gcc gcc /usr/bin/gcc-7 70 \
        --slave /usr/local/bin/g++ g++ /usr/bin/g++-7 \
        --slave /usr/local/bin/cpp gcc-cpp /usr/bin/cpp-7 \
        --slave /usr/local/bin/gfortran gfortran /usr/bin/gfortran-7 \
        --slave /usr/local/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-7 \
        --slave /usr/local/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-7 \
        --slave /usr/local/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-7 \
        --slave /usr/local/bin/gcov gcov /usr/bin/gcov-7 \
        --slave /usr/local/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-7
      sudo update-alternatives --install /usr/bin/cc cc /usr/local/bin/gcc 100
      sudo update-alternatives --install /usr/bin/c++ c++ /usr/local/bin/g++ 100
      sudo update-alternatives --install /lib/cpp cpp /usr/local/bin/cpp 100
      sudo update-alternatives --install /usr/bin/f77 f77 /usr/local/bin/gfortran 100
      sudo update-alternatives --install /usr/bin/f95 f95 /usr/local/bin/gfortran 100
    fi
    set +e
  - gcc --version
  - g++ --version
  - gfortran --version
  - |
    set -e
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      TRAVIS_PYTHON_VERSION="$(pyenv install --list | grep -E " ${TRAVIS_PYTHON_VERSION}(\.[0-9brc]+)+" | tail -n 1 | sed -e 's/^[[:space:]]*//')"
      pyenv install "${TRAVIS_PYTHON_VERSION}"
      export PATH="$HOME/.pyenv/versions/${TRAVIS_PYTHON_VERSION}/bin:${PATH}"
    fi
    set +e
  - |
    set -e
    if [[ "${TRAVIS_OS_NAME}" == "linux" && "${TRAVIS_PYTHON_VERSION}" != "3.7" ]]; then
      jdk_switcher use $TRAVIS_JDK_VERSION
    fi
    set +e
  # Open Fortran Compiler
  - git clone "https://github.com/codethinklabs/ofc" "../open-fortran-compiler"
  - |
    set -e
    cd "../open-fortran-compiler"
    CFLAGS="-Wno-implicit-fallthrough -Wno-maybe-uninitialized" make
    cd -
    set +e
  - export PATH="${PATH}:$(pwd)/../open-fortran-compiler"
  # FFB-MINI app
  - git clone "https://github.com/mbdevpl/ffb-mini" "../ffb-mini"
  # miranda_io app
  - git clone "https://github.com/mbdevpl/miranda_io" "../miranda_io"

install:
  - pip install -U pip
  # CastXML
  - |
    set -e
    git clone "https://github.com/CastXML/CastXML" "../CastXML"
    cd "../CastXML"
    cmake .
    make
    export PATH="$(pwd)/bin:${PATH}"
    cd -
    set +e
  # use OFP XML from repo
  - |
    set -e
    git clone "https://github.com/mbdevpl/open-fortran-parser-xml" "../open-fortran-parser-xml"
    cd "../open-fortran-parser-xml"
    pip install -U -r dev_requirements.txt
    python -m open_fortran_parser --dev-deps
    ant
    python setup.py bdist_wheel
    pip install -U dist/*.whl
    cd -
    set +e
  - pip install -U -r dev_requirements.txt

script:
  - TEST_PACKAGING=1 TEST_LONG=1 python -m coverage run --branch --source . -m unittest -v

after_success:
  - python -m coverage report --show-missing
  - codecov

notifications:
  slack:
    secure: "IJLucZng9JvlxZY6jm17YZ1Ehy528T47Gsz3ztYpZlZIvPCfprGPSK7Cj0kOQRpsSBw73aWXt+f9akggq81seQZabSahI/Lun5vKaoasuNveUElbnw0bsQRrpUyFrWH1pYQndxd6Rpd2YOek6fxS0+PbVoX4Gwg3Z7EDgfaL5MWdlmkEkUdwsZzSK+zmJyEWkWHeyCYd29760gRK85bzTBG/Y/yDrxS7xUnU5OgiUHg5U6LKfyoWKwSW0o2ljkCs72/xSVwYqPNg5MEixExfvmQgElnsp2Bn/KJcPa6HZYnTTsL1d0TBC59C3imRkSZztR1Fmg39r72Lq0W0EMdwJzTKwlGgYxdPuCfCdkM+rhmlOHjYwq56oWBOu+jT8vVbgNsxeFAEmqwtLJ7b7K4OCkiyFwdGWy9DvbJ2vhq4hwjRCMfXVDpTmgP7fNj8Tc05ZpnM8gwk9w54/Vv0taYFguocgj7VbNpJfl2cnQbRG3Zj/AQ5vtmkhDnU/0mDQ4j4lOQuuJ+BeJ0p6qEl1JVGYDRXBg/YfRdRR0uT/wY1gZNQwJ7byrgC0Al+WrRTXkB6ds9+/JlP5o9la7BImtaMOkUBkPCTg0XsRZ/aVTAHMPSrSrOxUXl4imTJHg7R75EYvtXo5aEnPLMorJldaZfTyZFLhf2nnYQ4K4WX3Cm8uQI="
  email: false
